---

- lineinfile: dest=/var/lib/dpkg/arch line="amd64" create=yes
- lineinfile: dest=/var/lib/dpkg/arch line="i386" create=yes
  register: add_i386
- apt: name={{item}} update_cache={{add_i386.changed}}
  with_items: ['libc6:i386', 'libstdc++6:i386', 'zlib1g:i386']

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: install the gdebi package manager which can process both local and remote packages
  become: true
  apt:
    name: gdebi
    state: present

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: "{{ my_package_url }}"
    dest: /usr/local/bin
    remote_src: yes

- name: Install my_package common
  apt: 
   deb: "/usr/local/bin/mysql-common_5.6.48-1debian9_amd64.deb"

- name: Install my_package community_client
  apt: 
   deb: "/usr/local/bin/{{ my_package_name_community_client }}.deb"

- name: Install my_package client
  apt: 
   deb: "/usr/local/bin/{{ my_package_name_client }}.deb"


- name: Install my_package community_server
  apt: 
   deb: "/usr/local/bin/mysql-community-server_5.6.48-1debian9_amd64.deb"









